# Generated by Django 5.1.7 on 2025-03-11 21:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Назва')),
                ('description', models.TextField(verbose_name='Опис')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ціна')),
                ('stock_quantity', models.IntegerField(verbose_name='Кількість на складі')),
                ('instrument_type', models.CharField(max_length=50, verbose_name='Тип інструменту')),
                ('image', models.ImageField(blank=True, null=True, upload_to='instruments/', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Інструмент',
                'verbose_name_plural': 'Інструменти',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='Кількість')),
                ('customer_name', models.CharField(max_length=100, verbose_name="Ім'я клієнта")),
                ('customer_email', models.EmailField(max_length=254, verbose_name='Електронна пошта клієнта')),
                ('order_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата замовлення')),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instruments.instrument', verbose_name='Інструмент')),
            ],
            options={
                'verbose_name': 'Замовлення',
                'verbose_name_plural': 'Замовлення',
            },
        ),
    ]
